//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanofi.DM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProcedimientosAlmacenados {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProcedimientosAlmacenados() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sanofi.DM.Resources.ProcedimientosAlmacenados", typeof(ProcedimientosAlmacenados).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanofi.Sp_ConsultaAthenaFiltros.
        /// </summary>
        internal static string Sp_ConsultaAthenaFiltros {
            get {
                return ResourceManager.GetString("Sp_ConsultaAthenaFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanofi.Sp_ConsultaErroresExcel.
        /// </summary>
        internal static string Sp_ConsultaErroresExcel {
            get {
                return ResourceManager.GetString("Sp_ConsultaErroresExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanofi.Sp_ConsultaGastosFiltros.
        /// </summary>
        internal static string Sp_ConsultaGastosFiltros {
            get {
                return ResourceManager.GetString("Sp_ConsultaGastosFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanofi.Sp_ConsultaRegistrosExitososAthena.
        /// </summary>
        internal static string Sp_ConsultaRegistrosExitososAthena {
            get {
                return ResourceManager.GetString("Sp_ConsultaRegistrosExitososAthena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanofi.Sp_ConsultaRegistrosExitososGastos.
        /// </summary>
        internal static string Sp_ConsultaRegistrosExitososGastos {
            get {
                return ResourceManager.GetString("Sp_ConsultaRegistrosExitososGastos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanofi.Sp_ConsultaRegistrosExitososSolped.
        /// </summary>
        internal static string Sp_ConsultaRegistrosExitososSolped {
            get {
                return ResourceManager.GetString("Sp_ConsultaRegistrosExitososSolped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanofi.Sp_ConsultaSolpedFiltros.
        /// </summary>
        internal static string Sp_ConsultaSolpedFiltros {
            get {
                return ResourceManager.GetString("Sp_ConsultaSolpedFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanofi.Sp_InsertarAthena.
        /// </summary>
        internal static string Sp_InsertarAthena {
            get {
                return ResourceManager.GetString("Sp_InsertarAthena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanofi.Sp_InsertarErrores.
        /// </summary>
        internal static string Sp_InsertarErrores {
            get {
                return ResourceManager.GetString("Sp_InsertarErrores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanofi.Sp_InsertarGastos.
        /// </summary>
        internal static string Sp_InsertarGastos {
            get {
                return ResourceManager.GetString("Sp_InsertarGastos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanofi.Sp_InsertarSolped.
        /// </summary>
        internal static string Sp_InsertarSolped {
            get {
                return ResourceManager.GetString("Sp_InsertarSolped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanofi.Sp_ListarGastosConcatenar.
        /// </summary>
        internal static string Sp_ListarGastosConcatenar {
            get {
                return ResourceManager.GetString("Sp_ListarGastosConcatenar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanofi.Sp_ListarGastosCuentas.
        /// </summary>
        internal static string Sp_ListarGastosCuentas {
            get {
                return ResourceManager.GetString("Sp_ListarGastosCuentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanofi.Sp_ListarGastosTipos.
        /// </summary>
        internal static string Sp_ListarGastosTipos {
            get {
                return ResourceManager.GetString("Sp_ListarGastosTipos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanofi.Sp_GenerarBase.
        /// </summary>
        internal static string Sp_ReporteConsolidado {
            get {
                return ResourceManager.GetString("Sp_ReporteConsolidado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanofi.Sp_ReportesAthena.
        /// </summary>
        internal static string Sp_ReportesAthena {
            get {
                return ResourceManager.GetString("Sp_ReportesAthena", resourceCulture);
            }
        }
    }
}
